name: dontnet Mvc to CI Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
               
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      
      - name: Build and Publish Web App
        run: msbuild ./dotnetMVC/dotnetMVC.sln /p:Configuration=Release /p:DeployOnBuild=true

      # Runs a set of commands using the runners shell
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: published_webapp
          path: bin\Release\Publish
