name: Use ubuntu On github Action

on:
  push:
    branches: [ dev_pull_request ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and deploy gh-pages
    env:
        MY_SECRET   : ${{secrets.commit_secret}}
        USER_NAME   : github-actions[bot]
        USER_EMAIL  : 41898282+github-actions[bot]@users.noreply.github.com
        PUBLISH_DIR : ./dotnetMVC/dotnetMvcUnitTests/bin/Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
              
      - name: test git 
        run: |
          git config --local user.name $USER_NAME
          git config --local user.email $USER_EMAIL
          git remote set-url origin https://github.com/JontCont/dotnetMvc_Deploy.git
          git config --list
          

